import { useEffect, useState } from 'react';
import { Plus, Edit2, Trash2, X, Search } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import type { Database } from '@/integrations/supabase/types';
import ListLoadingSkeleton from './ListLoadingSkeleton';

type CompanyRow = Database['public']['Tables']['company']['Row'];

// id is optional since it's auto-generated by the DB
type CompanyFormData = {
  company: string;
  company_name: string;
};

export default function CompanyList() {
  const [companies, setCompanies] = useState<CompanyRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [editingCompany, setEditingCompany] = useState<CompanyRow | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [isMobile, setIsMobile] = useState(false);
  const [formData, setFormData] = useState<CompanyFormData>({
    company: '',
    company_name: '',
  });

  useEffect(() => { fetchCompanies(); }, []);

  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 768);
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  const fetchCompanies = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase.from('company').select('*');
      if (error) throw error;
      setCompanies(data || []);
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch companies.', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  const handleAddCompany = () => {
    setEditingCompany(null);
    setFormData({ company: '', company_name: '' });
    setShowModal(true);
  };

  const handleEdit = (company: CompanyRow) => {
    setEditingCompany(company);
    setFormData({
      company: company.company || '',
      company_name: company.company_name || '',
    });
    setShowModal(true);
  };

  const handleSaveCompany = async () => {
    try {
      if (editingCompany) {
        // UPDATE — id is not sent, we just match by it
        const { data, error } = await supabase
          .from('company')
          .update(formData)
          .eq('id', editingCompany.id)
          .select();
        if (error) throw error;
        setCompanies(companies.map((c) => (c.id === editingCompany.id ? data[0] : c)));
        toast({ title: 'Success', description: 'Company updated successfully' });
      } else {
        // INSERT — id is auto-generated, not included
        const { data, error } = await supabase
          .from('company')
          .insert([formData])
          .select();
        if (error) throw error;
        setCompanies([...companies, ...data]);
        toast({ title: 'Success', description: 'Company added successfully' });
      }
      setShowModal(false);
      setEditingCompany(null);
      setFormData({ company: '', company_name: '' });
    } catch {
      toast({ title: 'Error', description: 'Failed to save company', variant: 'destructive' });
    }
  };

  const handleDelete = async (id: number) => {
    if (!confirm('Are you sure you want to delete this company?')) return;
    const { error } = await supabase.from('company').delete().eq('id', id);
    if (error) {
      toast({ title: 'Error', description: 'Failed to delete company', variant: 'destructive' });
    } else {
      setCompanies(companies.filter((c) => c.id !== id));
      toast({ title: 'Deleted', description: 'Company deleted successfully' });
    }
  };

  const filteredCompanies = companies
    .filter((c) => {
      const q = searchQuery.toLowerCase();
      return (
        String(c.id).includes(q) ||
        c.company?.toLowerCase().includes(q) ||
        c.company_name?.toLowerCase().includes(q)
      );
    })
    .sort((a, b) => a.id - b.id);

  if (loading) {
    return (
      <ListLoadingSkeleton
        isMobile={isMobile}
        title="COMPANY LIST"
        tableColumns={4}
        mainClassName="p-6"
        showFilters={false}
        showActionButton
      />
    );
  }

  return (
    <div className="h-full bg-background flex flex-col">
      {isMobile ? (
        /* ── Mobile Layout ── */
        <div className="fixed inset-x-0 top-0 bottom-0 flex flex-col" style={{ paddingTop: '60px' }}>
          <div className="flex-shrink-0 bg-background border-b border-border">
            <div className="flex flex-col items-start justify-between gap-3 p-4 pb-3">
              <div className="flex items-center justify-between w-full">
                <h2 className="text-lg font-semibold text-foreground">COMPANY LIST</h2>
                <button
                  onClick={handleAddCompany}
                  className="flex items-center gap-2 bg-blue-600 text-white px-3 py-2 rounded-lg hover:bg-blue-700 transition-colors text-sm"
                >
                  <Plus size={18} />
                  Add
                </button>
              </div>
              <div className="relative w-full">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search companies..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10 w-full bg-input border-border text-sm"
                />
              </div>
            </div>
          </div>

          <div className="flex-1 overflow-auto p-4">
            <div className="space-y-3 pb-6">
              {filteredCompanies.length === 0 ? (
                <div className="text-center py-12 text-muted-foreground">No companies found</div>
              ) : (
                filteredCompanies.map((c) => (
                  <Card key={c.id} className="bg-card border-border" onClick={() => handleEdit(c)}>
                    <CardContent className="p-4">
                      <div className="flex justify-between items-start mb-3">
                        <div className="text-primary font-semibold text-sm">#{c.id}</div>
                        <div className="flex gap-2">
                          <button
                            onClick={(e) => { e.stopPropagation(); handleEdit(c); }}
                            className="p-1.5 text-blue-500 hover:bg-blue-50 rounded transition-colors"
                          >
                            <Edit2 size={16} />
                          </button>
                          <button
                            onClick={(e) => { e.stopPropagation(); handleDelete(c.id); }}
                            className="p-1.5 text-red-500 hover:bg-red-50 rounded transition-colors"
                          >
                            <Trash2 size={16} />
                          </button>
                        </div>
                      </div>
                      <div className="space-y-2">
                        <div>
                          <div className="text-xs text-muted-foreground uppercase tracking-wide">Company Code</div>
                          <div className="text-sm text-foreground mt-0.5">{c.company || '-'}</div>
                        </div>
                        <div>
                          <div className="text-xs text-muted-foreground uppercase tracking-wide">Company Name</div>
                          <div className="text-sm text-foreground mt-0.5">{c.company_name || '-'}</div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))
              )}
            </div>
          </div>
        </div>
      ) : (
        /* ── Desktop Layout ── */
        <>
          <div className="flex items-center justify-between px-4 py-4 bg-background border-b border-gray-700">
            <h2 className="text-xl font-semibold text-foreground">COMPANY LIST</h2>
            <div className="flex items-center gap-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10 w-64 bg-input border-border transition-all duration-300 hover:w-80 focus:w-80"
                />
              </div>
              <button
                onClick={handleAddCompany}
                className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
              >
                <Plus size={20} />
                Add Company
              </button>
            </div>
          </div>

          <div className="flex flex-col bg-gray-800 mx-4 mb-4 mt-4 rounded-lg shadow overflow-hidden flex-1">
            <div className="flex-1 overflow-y-auto custom-scrollbar">
              <table className="w-full table-auto">
                <thead className="bg-gray-900 sticky top-0 z-10">
                  <tr>
                    <th className="text-left px-6 py-4 text-sm font-semibold text-gray-300 w-20">ID</th>
                    <th className="text-left px-6 py-4 text-sm font-semibold text-gray-300">Company Code</th>
                    <th className="text-left px-6 py-4 text-sm font-semibold text-gray-300">Company Name</th>
                    <th className="text-left px-6 py-4 text-sm font-semibold text-gray-300 w-32">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-700">
                  {filteredCompanies.length === 0 ? (
                    <tr>
                      <td colSpan={4} className="px-6 py-10 text-center text-gray-500 italic text-sm">
                        No companies found
                      </td>
                    </tr>
                  ) : (
                    filteredCompanies.map((c) => (
                      <tr key={c.id} className="hover:bg-gray-700 transition-colors cursor-pointer" onDoubleClick={() => handleEdit(c)}>
                        <td className="px-6 py-4 text-gray-400 text-sm">{c.id}</td>
                        <td className="px-6 py-4 text-gray-200">{c.company}</td>
                        <td className="px-6 py-4 text-gray-200">{c.company_name}</td>
                        <td className="px-6 py-4 w-32">
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => handleEdit(c)}
                              className="p-1.5 text-gray-400 hover:text-blue-400 hover:bg-gray-700 rounded transition-colors"
                              title="Edit"
                            >
                              <Edit2 size={18} />
                            </button>
                            <button
                              onClick={() => handleDelete(c.id)}
                              className="p-1.5 text-gray-400 hover:text-red-400 hover:bg-gray-700 rounded transition-colors"
                              title="Delete"
                            >
                              <Trash2 size={18} />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </>
      )}

      {/* ── Modal ── */}
      {showModal && (
        <div className="fixed inset-0 flex items-center justify-center z-50 bg-black/50 p-4">
          <div className="bg-gray-800 rounded-lg p-6 w-full max-w-md text-white">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">
                {editingCompany ? 'Edit Company' : 'Add Company'}
              </h3>
              <button onClick={() => setShowModal(false)}>
                <X size={20} />
              </button>
            </div>

            <div className="space-y-3">
              {editingCompany && (
                <div className="flex flex-col">
                  <label className="text-sm mb-1 text-gray-400">ID (auto-generated)</label>
                  <input
                    type="number"
                    className="px-3 py-2 rounded bg-gray-600 text-gray-400 cursor-not-allowed opacity-60"
                    value={editingCompany.id}
                    disabled
                  />
                </div>
              )}
              <div className="flex flex-col">
                <label className="text-sm mb-1">Company Code</label>
                <input
                  type="text"
                  className="px-3 py-2 rounded bg-gray-700 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                  value={formData.company}
                  onChange={(e) => setFormData({ ...formData, company: e.target.value })}
                />
              </div>
              <div className="flex flex-col">
                <label className="text-sm mb-1">Company Name</label>
                <input
                  type="text"
                  className="px-3 py-2 rounded bg-gray-700 text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                  value={formData.company_name}
                  onChange={(e) => setFormData({ ...formData, company_name: e.target.value })}
                />
              </div>
            </div>

            <div className="mt-6 flex justify-end gap-2">
              <button
                onClick={() => setShowModal(false)}
                className="px-4 py-2 rounded bg-gray-600 hover:bg-gray-500"
              >
                Cancel
              </button>
              <button
                onClick={handleSaveCompany}
                className="px-4 py-2 rounded bg-blue-600 hover:bg-blue-700"
              >
                {editingCompany ? 'Update' : 'Save'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
